language: php

php:
  - 7.1
  - 7.2

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -u root -e 'create database laravelAuth;'
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan vendor:publish --tag=laraveltidytables.config
  - php artisan key:generate
  - php artisan migrate:install --env=testing --no-interaction
  - composer dump-autoload
  
  script: vendor/bin/phpunit
