language: php

php:
  - 7.1
  - 7.2

sudo: false

before_install:
  - phpenv config-rm xdebug.ini || true

install: composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit 
